apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-backend
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-backend
  template:
    metadata:
      labels:
        app: mongo-backend
    spec:
      containers:
        - name: backend
          image: rsemihkoca/itumik_mongo:v0.1.4
          ports:
            - containerPort: 8000
          env:
          - name: CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: mongo-secrets
                key: CONNECTION_STRING
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-backend-service
  namespace: backend
spec:
  selector:
    app: mongo-backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
